### ISSUE TITLE
Minor error in report_tabs.R

### ISSUE THREAD

**Issue by hazimtimimi** [glaziou/gtb2016#1]
Philippe,

I think line #139 in report_tabs.R needs changing from 

    tab1bs[, 9:14] <- signif(tab1bs[, 9:14]*100,3)

to

    tab1bs[, 12:14] <- signif(tab1bs[, 9:14]*100,3) 

because at the moment incidence estimates are inflated by a factor of 100 in the tabular output!

**Comment by glaziou** [comment]
now fixed - thanks
